return {
	-- Highlight, edit, and navigate code
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPost", "BufNewFile" },
	build = ":TSUpdate | TSInstallAll",
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"cmake",
			"comment",
			"cpp",
			"diff",
			"doxygen",
			"html",
			"json",
			"lua",
			"luadoc",
			"make",
			"markdown",
			"markdown_inline",
			"printf",
			"python",
			"regex",
			"rust",
			"sql",
			"typst",
			"vimdoc",
			"yaml",
		},
	},
}
