#!/usr/bin/env zsh

git clone -q --depth=1 https://github.com/ohmyzsh/ohmyzsh.git $ZDOTDIR/.oh-my-zsh
git clone -q --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git $ZDOTDIR/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone -q --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git $ZDOTDIR/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone -q --depth=1 https://github.com/romkatv/powerlevel10k.git $ZDOTDIR/.oh-my-zsh/custom/themes/powerlevel10k

() {
	local f
	for f in ~/.oh-my-zsh/{oh-my-zsh.sh,**/*.zsh}; do
		zcompile -R -- "$f".zwc "$f"
	done
}

make -s -C $ZDOTDIR/.oh-my-zsh/custom/themes/powerlevel10k pkg
